export const CHANGE_TITLE_FIELD = 'CHANGE_TITLE_FIELD';
export const CHANGE_TAGS_FIELD = 'CHANGE_TAGS_FIELD';
export const CHANGE_SERVINGS_FIELD = 'CHANGE_SERVINGS_FIELD';
export const CHANGE_INGREDIENTS_FIELD = 'CHANGE_INGREDIENTS_FIELD';
export const CHANGE_INSTRUCTIONS_FIELD = 'CHANGE_INSTRUCTIONS_FIELD';
export const CHANGE_PREP_TIME_FIELD = 'CHANGE_PREP_TIME_FIELD';
export const CHANGE_COOK_TIME_FIELD = 'CHANGE_COOK_TIME_FIELD';
export const CHANGE_READY_IN_FIELD = 'CHANGE_READY_IN_FIELD';
export const CHANGE_DESCRIPTION_FIELD = 'CHANGE_DESCRIPTION_FIELD';
export const CHANGE_IMG_FIELD = 'CHANGE_IMG_FIELD';
export const CHANGE_EMAIL_FIELD = 'CHANGE_EMAIL_FIELD';
export const CHANGE_PASSWORD_FIELD = 'CHANGE_PASSWORD_FIELD';
export const CHANGE_CONFIRM_PASSWORD_FIELD = 'CHANGE_CONFIRM_PASSWORD_FIELD';

export const REQUEST_RECIPE_PENDING = 'REQUEST_RECIPE_PENDING';
export const REQUEST_RECIPE_SUCCESS = 'REQUEST_RECIPE_SUCCESS';
export const REQUEST_RECIPE_FAILED = 'REQUEST_RECIPE_FAILED';

export const REQUEST_USER_PENDING = 'REQUEST_USER_PENDING';
export const REQUEST_USER_SUCCESS = 'REQUEST_USER_SUCCESS';
export const REQUEST_USER_FAILED = 'REQUEST_USER_FAILED';
